### ISSUE TITLE
Add a licence 

### ISSUE THREAD

**Issue by jcoyne** [lulibrary/doi#12]
Is this project available for use by others?  If so, it would be great if you added a `LICENSE` file with the terms you are granting.  There's some help here if you can't decide which license to use: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by stephenrob** [comment]
I've added the MIT license to this project in-keeping with most of our other open sourced software. Hope you find this useful @jcoyne

**Comment by jcoyne** [comment]
Thank you.
